name: tool_transfer_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchaudio
  - torchvision
  - jupyter
  - scikit-learn
  - matplotlib
  - librosa
  - opencv=4.6.0
  - pandas
  - seaborn
  - scikit-image
  - numpy
